-- 修补缺失的 PACKAGE BODY OB_SHARE.PKG_DATA_ROUTER (源: ORA_UTIL.PKG_DATA_ROUTER)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE PACKAGE BODY "OB_SHARE"."PKG_DATA_ROUTER" AS
    PROCEDURE REFRESH_REGION_CACHE IS
    BEGIN
        NULL;
    END;

    FUNCTION COUNT_ORDERS_BY_REGION(p_region_code VARCHAR2) RETURN NUMBER IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_cnt
          FROM OB_SHARE.SYN_ORDER o
          JOIN OB_SHARE.SYN_CUSTOMER c ON c.CUSTOMER_ID = o.CUSTOMER_ID
          JOIN OB_SHARE.SYN_REGION r ON r.REGION_ID = c.REGION_ID
         WHERE r.REGION_CODE = p_region_code;
        RETURN v_cnt;
    END;
END PKG_DATA_ROUTER;