-- 授予 OB_SHARE 访问 remap 依赖目标的权限
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

GRANT EXECUTE ON OB_FIN.SP_POST_INVOICE TO OB_SHARE;
GRANT SELECT ON OB_APP.F_ORDER TO OB_SHARE;
GRANT SELECT ON OB_DIM.REGION_DIM TO OB_SHARE;
GRANT SELECT ON OB_LEDGER.INVOICE_HEADER TO OB_SHARE;
