-- 修补缺失的 PROCEDURE OB_AUDIT.SP_ARCHIVE_AUDIT (源: ORA_LOG.SP_ARCHIVE_AUDIT)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE PROCEDURE "OB_AUDIT"."SP_ARCHIVE_AUDIT" (
    p_cleanup_days IN NUMBER
) AS
BEGIN
    INSERT INTO OB_AUDIT.AUDIT_ARCHIVE
    SELECT *
      FROM OB_AUDIT.AUDIT_EVENTS
     WHERE EVENT_TS < SYSDATE - p_cleanup_days;
END;