-- 修补缺失的 FUNCTION OB_APP.FN_CUSTOMER_SCORE (源: ORA_SALES.FN_CUSTOMER_SCORE)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE FUNCTION "OB_APP"."FN_CUSTOMER_SCORE" (
    p_customer_id IN NUMBER
) RETURN NUMBER IS
    v_score NUMBER;
BEGIN
    SELECT NVL(SUM(ORDER_TOTAL), 0) INTO v_score
      FROM OB_DW.F_ORDER_METRIC
     WHERE CUSTOMER_ID = p_customer_id
       AND STATUS = 'C';
    RETURN v_score;
END;