-- 修补缺失的 FUNCTION OB_AUDIT.FN_LAST_AUDIT_ID (源: ORA_LOG.FN_LAST_AUDIT_ID)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE FUNCTION "OB_AUDIT"."FN_LAST_AUDIT_ID" RETURN NUMBER IS
    v_id NUMBER;
BEGIN
    SELECT NVL(MAX(EVENT_ID), 0) INTO v_id FROM OB_AUDIT.AUDIT_EVENTS;
    RETURN v_id;
END;