-- 修补缺失的 MATERIALIZED VIEW OB_ANALYTICS.MV_EVENT_AGG (源: ORA_DIGITAL.MV_EVENT_AGG)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_ANALYTICS;

CREATE MATERIALIZED VIEW "OB_ANALYTICS"."MV_EVENT_AGG" (
	"EVENT_TYPE",
	"EVENT_DAY",
	"EVENT_COUNT")
REFRESH COMPLETE ON DEMAND
 AS 
SELECT EVENT_TYPE,
       TRUNC(EVENT_TS) AS EVENT_DAY,
       COUNT(*) AS EVENT_COUNT
  FROM OB_STREAM.STREAM_EVENT
 GROUP BY EVENT_TYPE, TRUNC(EVENT_TS);
