-- 修补缺失的 MATERIALIZED VIEW OB_RPT.MV_MARGIN_ROLLUP (源: ORA_RPT.MV_MARGIN_ROLLUP)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_RPT;

CREATE MATERIALIZED VIEW "OB_RPT"."MV_MARGIN_ROLLUP" (
	"REGION_NAME",
	"TOTAL_AMOUNT")
REFRESH COMPLETE ON DEMAND
 AS 
SELECT r.REGION_NAME,
       SUM(o.ORDER_TOTAL) AS TOTAL_AMOUNT
  FROM OB_APP.F_ORDER o
  JOIN OB_DIM.REGION_DIM r ON o.REGION_ID = r.REGION_ID
 GROUP BY r.REGION_NAME;
