-- Spiderweb remap target-side DDL (OceanBase Oracle-compatible tenant)
-- Run as a privileged user inside the OceanBase tenant that will hold the migrated objects.
SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE;

PROMPT === Creating target schemas / users ===

CREATE USER OB_STAGE IDENTIFIED BY ob_stage_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_STAGE;

CREATE USER OB_ODS IDENTIFIED BY ob_ods_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_ODS;

CREATE USER OB_DW IDENTIFIED BY ob_dw_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_DW;

CREATE USER OB_APP IDENTIFIED BY ob_app_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_APP;

CREATE USER OB_AUDIT IDENTIFIED BY ob_audit_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_AUDIT;

CREATE USER OB_SHARE IDENTIFIED BY ob_share_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_SHARE;

CREATE USER ORA_SEC IDENTIFIED BY ora_sec_pass;
GRANT CONNECT, RESOURCE, DBA TO ORA_SEC;

PROMPT === OB_STAGE lookup targets ===

CREATE TABLE OB_STAGE.REGION_DIM (
    REGION_ID     NUMBER(6) PRIMARY KEY,
    REGION_CODE   VARCHAR2(20)  NOT NULL,
    REGION_NAME   VARCHAR2(100) NOT NULL,
    ACTIVE_FLAG   VARCHAR2(1)   DEFAULT 'Y',
    MIGRATED_BY   VARCHAR2(30)  DEFAULT 'UNKNOWN'
);
-- Unique constraint on REGION_CODE intentionally omitted

CREATE TABLE OB_STAGE.SHIP_METHOD (
    SHIP_METHOD_ID    NUMBER(4) PRIMARY KEY,
    SHIP_METHOD_CODE  VARCHAR2(20) NOT NULL,
    SHIP_METHOD_NAME  VARCHAR2(80) NOT NULL,
    REGION_ID         NUMBER(6)
);
-- Foreign key to REGION_DIM intentionally omitted

CREATE SEQUENCE OB_STAGE.SEQ_REGION START WITH 100 INCREMENT BY 2;

PROMPT === OB_ODS dimension tables (incomplete on purpose) ===

CREATE TABLE OB_ODS.CUST_DIM (
    CUSTOMER_ID    NUMBER(10) PRIMARY KEY,
    CUSTOMER_CODE  VARCHAR2(30)  NOT NULL,
    CUSTOMER_NAME  VARCHAR2(120) NOT NULL,  -- should have been 180
    EMAIL          VARCHAR2(180),           -- should have been 270
    STATUS         VARCHAR2(1)   DEFAULT 'A',
    REGION_ID      NUMBER(6)     NOT NULL,
    CREDIT_LIMIT   NUMBER(12,2),
    CREATED_AT     DATE          DEFAULT SYSDATE,
    UPDATED_AT     DATE
);
-- VIP_FLAG column and FK to REGION_DIM are missing by design

PROMPT === OB_DW fact tables / sequences ===

CREATE TABLE OB_DW.F_ORDER_METRIC (
    ORDER_ID        NUMBER(12),
    ORDER_CODE      VARCHAR2(40),     -- should be 60 after 1.5× expansion
    CUSTOMER_ID     NUMBER(10) NOT NULL,
    SHIP_METHOD_ID  NUMBER(4),
    ORDER_TOTAL     NUMBER(14,2),
    DISCOUNT_RATE   NUMBER(5,2),
    STATUS          VARCHAR2(1) DEFAULT 'N',
    CREATED_AT      DATE,
    UPDATED_AT      DATE
);
-- ORDER_NOTE column, STATUS check constraint, PK/FK definitions, and indexes are missing

CREATE SEQUENCE OB_DW.SEQ_F_ORDER START WITH 70000 INCREMENT BY 5;
CREATE SEQUENCE OB_DW.EXTRA_ORPHAN_SEQ START WITH 1 INCREMENT BY 1; -- extra object to trigger "extra sequence"

CREATE INDEX OB_DW.IDX_F_ORDER_STATUS ON OB_DW.F_ORDER_METRIC (STATUS);
-- This index does not exist in Oracle; added to test "extra index" reporting.

PROMPT === OB_APP program units (partial deployment) ===

CREATE OR REPLACE PACKAGE OB_APP.PKG_ORDER_MGMT AS
    PROCEDURE QUEUE_ORDER(p_order_id NUMBER, p_status VARCHAR2);
    PROCEDURE CLOSE_ORDER(p_order_id NUMBER);
    FUNCTION COUNT_BY_STATUS(p_status VARCHAR2) RETURN NUMBER;
END Pkg_Order_Mgmt;
/
-- Package body intentionally not created
-- SP_CREATE_ORDER and FN_CUSTOMER_SCORE are intentionally missing

PROMPT === OB_AUDIT audit structures (purposely incomplete) ===

CREATE TABLE OB_AUDIT.AUDIT_EVENTS (
    EVENT_ID       NUMBER(12),
    SOURCE_SCHEMA  VARCHAR2(30),
    OBJECT_NAME    VARCHAR2(50),
    EVENT_TYPE     VARCHAR2(20),
    EVENT_TS       DATE,
    DETAIL         VARCHAR2(2000)
);
-- No PK, sequence, trigger, or PL/SQL wrapper

CREATE TABLE OB_AUDIT.ERROR_LOG (
    ERROR_ID      NUMBER(12),
    ERROR_CODE    VARCHAR2(20),
    ERROR_MESSAGE VARCHAR2(400),  -- should have been 600 to satisfy 1.5× rule
    CREATED_BY    VARCHAR2(30),
    CREATED_AT    DATE
);
-- Missing PK and IDX_ERROR_LOG_CODE on purpose

CREATE TABLE OB_AUDIT.AUDIT_ARCHIVE AS
SELECT * FROM OB_AUDIT.AUDIT_EVENTS WHERE 1 = 2;

CREATE SEQUENCE OB_AUDIT.SEQ_ERROR START WITH 1 INCREMENT BY 1;
-- SEQ_AUDIT is intentionally not created

PROMPT === OB_SHARE integration layer objects (partial) ===

CREATE SYNONYM OB_SHARE.SYN_REGION FOR OB_STAGE.REGION_DIM;
-- SYN_CUSTOMER and SYN_ORDER are intentionally missing

-- Views and the PKG_DATA_ROUTER package pair are omitted to force missing-object findings

PROMPT === ORA_SEC (1:1 migrated schema) ===

CREATE TABLE ORA_SEC.USER_MATRIX (
    USERNAME      VARCHAR2(60)  NOT NULL,
    LAST_LOGIN    DATE,
    STATUS        VARCHAR2(20)  NOT NULL,
    ATTEMPTS      NUMBER(3)     DEFAULT 0,
    LOCK_REASON   VARCHAR2(200),
    CONSTRAINT PK_USER_MATRIX PRIMARY KEY (USERNAME)
);

CREATE OR REPLACE VIEW ORA_SEC.VW_LOGIN_FAILURE AS
SELECT USERNAME, LAST_LOGIN, STATUS, ATTEMPTS
  FROM ORA_SEC.USER_MATRIX
 WHERE STATUS = 'LOCKED';

PROMPT === OceanBase target definition complete ===
COMMIT;
