-- 修补缺失的约束 SYS_C009018 (表: OB_DATA.DEPARTMENTS, 源表: ORA_DATA.DEPARTMENTS)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER TABLE "OB_DATA"."DEPARTMENTS" ADD PRIMARY KEY ("DEPT_ID")
  USING INDEX  ENABLE;
