-- 修补缺失的约束 FK_ORDER_FACT_CUSTOMER (表: OB_DW.F_ORDER_METRIC)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER TABLE "OB_DW"."F_ORDER_METRIC" ADD CONSTRAINT "FK_ORDER_FACT_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "OB_ODS"."CUST_DIM" ("CUSTOMER_ID") ENABLE

-- 提示: 外键引用对象需要授权，执行以下语句：
-- GRANT REFERENCES ON OB_ODS.CUST_DIM TO OB_DW;