-- 修补缺失的约束 FK_CUSTOMER_DIM_REGION (表: OB_ODS.CUST_DIM)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER TABLE "OB_ODS"."CUST_DIM" ADD CONSTRAINT "FK_CUSTOMER_DIM_REGION" FOREIGN KEY ("REGION_ID")
	  REFERENCES "OB_STAGE"."REGION_DIM" ("REGION_ID") ENABLE

-- 提示: 外键引用对象需要授权，执行以下语句：
-- GRANT REFERENCES ON OB_STAGE.REGION_DIM TO OB_ODS;