-- 修补缺失的触发器 TRG_AUDIT_EVENTS_BI (表: OB_AUDIT.AUDIT_EVENTS)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE TRIGGER "OB_AUDIT"."TRG_AUDIT_EVENTS_BI" 
BEFORE INSERT ON OB_AUDIT.AUDIT_EVENTS
FOR EACH ROW
BEGIN
    IF :NEW.EVENT_ID IS NULL THEN
        SELECT OB_AUDIT.SEQ_AUDIT.NEXTVAL INTO :NEW.EVENT_ID FROM DUAL;
    END IF;
END;
ALTER TRIGGER "OB_AUDIT"."TRG_AUDIT_EVENTS_BI" ENABLE;
