-- 修补缺失的触发器 TRG_ORDER_FACT_BI (表: OB_DW.F_ORDER_METRIC)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE TRIGGER "OB_DW"."TRG_ORDER_FACT_BI" 
BEFORE INSERT ON OB_DW.F_ORDER_METRIC
FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        SELECT OB_DW.SEQ_F_ORDER.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
    END IF;
    IF :NEW.ORDER_CODE IS NULL THEN
        :NEW.ORDER_CODE := 'ORD-' || TO_CHAR(OB_DW.SEQ_F_ORDER.NEXTVAL);
    END IF;
END;
ALTER TRIGGER "OB_DW"."TRG_ORDER_FACT_BI" ENABLE;
