-- 修补缺失的触发器 TRG_SALES_BI (表: OB_DATA.SALES)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE TRIGGER "OB_DATA"."TRG_SALES_BI" 
BEFORE INSERT ON ORA_DATA.SALES
FOR EACH ROW
BEGIN
    :NEW.SALE_ID := NVL(:NEW.SALE_ID, 0);
END;
ALTER TRIGGER "ORA_DATA"."TRG_SALES_BI" ENABLE;
