-- 基于列差异的 ALTER TABLE 修补脚本: OB_STAGE.CHANNEL_DIM (源: ORA_REF.CHANNEL_DIM)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_STAGE;

-- 列长度不匹配 (目标端长度需在 [ceil(src*1.5), ceil(src*2.5)] 区间)：
-- WARNING: CHANNEL_NAME 长度过大 (源=60, 目标=300, 建议上限=150)，请人工评估是否需要收敛。
ALTER TABLE OB_STAGE.CHANNEL_DIM MODIFY (CHANNEL_CODE VARCHAR(18)); -- 源长度: 12, 目标长度: 12, 期望下限: 18

-- 目标端存在而源端不存在的列，以下 DROP COLUMN 为建议操作，请谨慎执行：
-- ALTER TABLE OB_STAGE.CHANNEL_DIM DROP COLUMN MIGRATION_TAG;
-- ALTER TABLE OB_STAGE.CHANNEL_DIM DROP COLUMN OMS_AUDIT_NOTE;
-- ALTER TABLE OB_STAGE.CHANNEL_DIM DROP COLUMN OMS_EXTRA_FLAG;
