-- 修补缺失的 VIEW OB_APP.V_EMP_DEPT (源: ORA_APP.V_EMP_DEPT)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OB_APP"."V_EMP_DEPT" ("NAME", "DEPT_NAME") AS 
  SELECT
    e.NAME,
    d.DEPT_NAME
FROM
    ORA_DATA.EMPLOYEES e
JOIN
    ORA_DATA.DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID;
