-- 修补缺失的 VIEW OB_DW.VW_HOT_CUST (源: ORA_SALES.VW_HOT_CUSTOMERS)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OB_DW"."VW_HOT_CUST" ("CUSTOMER_ID", "CUSTOMER_NAME", "STATUS", "TOTAL_SALES") AS 
  SELECT c.CUSTOMER_ID,
       c.CUSTOMER_NAME,
       c.STATUS,
       SUM(o.ORDER_TOTAL) AS TOTAL_SALES
  FROM OB_ODS.CUST_DIM c
  JOIN OB_DW.F_ORDER_METRIC o ON o.CUSTOMER_ID = c.CUSTOMER_ID
 WHERE o.STATUS = 'C'
 GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.STATUS;
