-- 修补缺失的 VIEW OB_SHARE.VW_CUSTOMER_REGION (源: ORA_UTIL.VW_CUSTOMER_REGION)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OB_SHARE"."VW_CUSTOMER_REGION" ("CUSTOMER_ID", "CUSTOMER_NAME", "REGION_CODE", "REGION_NAME", "ORDER_CNT", "TOTAL_SALES") AS 
  SELECT c.CUSTOMER_ID,
       c.CUSTOMER_NAME,
       r.REGION_CODE,
       r.REGION_NAME,
       COUNT(o.ORDER_ID) AS ORDER_CNT,
       NVL(SUM(o.ORDER_TOTAL),0) AS TOTAL_SALES
  FROM OB_SHARE.SYN_CUSTOMER c
  LEFT JOIN OB_SHARE.SYN_REGION r ON r.REGION_ID = c.REGION_ID
  LEFT JOIN OB_SHARE.SYN_ORDER o ON o.CUSTOMER_ID = c.CUSTOMER_ID
 GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, r.REGION_CODE, r.REGION_NAME;
